SELECT * FROM EMPLOYEES ; 

SELECT UPPER(FIRST_NAME), LOWER(LAST_NAME) FROM EMPLOYEES ; 

-- GET PART OF THE CHARACTER INSIDE WORD
-- THERE IS NO 0 INDEX CONCEPT IN SQL , INDEX ALWAYS START WITH ONE , ENDING INDEX INLCLUDED
SELECT SUBSTR( FIRST_NAME , 1 , 2 ) FROM EMPLOYEES ; 

-- GET THE INITIAL OF A STRING
SELECT SUBSTR( FIRST_NAME , 1 , 1 ) FROM EMPLOYEES ; 
-- GET INITIAL IN LOWERCASE

SELECT SUBSTR(  LOWER(FIRST_NAME) , 1 , 1 ) FROM EMPLOYEES ; 

SELECT LOWER (SUBSTR(FIRST_NAME,1,1) ) FROM EMPLOYEES ; 

-- HOW TO GET INITIAL AS THIRD COLUMN IF A TABLE HAVE FIRST_NAME AND LAST_NAME COLUMN 
-- FIRST_NAME , LAST_NAME , FULL_NAME ,  INITIALS

SELECT first_name, last_name, first_name|| ' ' ||last_name AS FULL_NAME
from employees ; 

SELECT SUBSTR( FIRST_NAME , 1 , 1 )|| SUBSTR( LAST_NAME , 1 , 1 ) AS INITIALS
from employees ; 


SELECT first_name, last_name, 
            first_name|| ' ' ||last_name AS FULL_NAME,
            SUBSTR( FIRST_NAME , 1 , 1 )|| SUBSTR( LAST_NAME , 1 , 1 ) AS INITIALS
            from employees ; 






SELECT COUNT(*) FROM EMPLOYEES ; 